/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion;

import Gestion.UnidadOrganizativa;
import Gestion.Cargo;
import Util.ValidaLetras;
import Util.ValidaNumeros;
import Gestion.CategoriaOcuapcional;
import Gestion.CapitalHumano;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class InsertarCargo extends javax.swing.JFrame {

    /**
     * Creates new form InsertarCargo
     */
    public InsertarCargo() {
        initComponents();
       
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width - getWidth()) / 2, (screenSize.height - getHeight())/ 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        grupoescala = new javax.swing.JLabel();
        salario = new javax.swing.JLabel();
        resolusion = new javax.swing.JLabel();
        calif = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        nombrejTextField1 = new javax.swing.JTextField();
        GrupoescalajTextField1 = new javax.swing.JTextField();
        salariojTextField1 = new javax.swing.JTextField();
        resolusionjTextField1 = new javax.swing.JTextField();
        califjComboBox1 = new javax.swing.JComboBox();
        tipojComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insertar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreco = new javax.swing.JComboBox();
        nombreuo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar Cargo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        nombre.setText("Nombre:");

        grupoescala.setText("Grupo de Escala:");

        salario.setText("Salario:");

        resolusion.setText("Resolución:");

        calif.setText("Calificación:");

        tipo.setText("Tipo:");

        nombrejTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombrejTextField1KeyPressed(evt);
            }
        });

        GrupoescalajTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GrupoescalajTextField1KeyPressed(evt);
            }
        });

        salariojTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salariojTextField1KeyPressed(evt);
            }
        });

        califjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Obrero Calificado", "Nivel Medio", "Nivel Superior", "Master", "Doctor" }));

        tipojComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Funcionario", "Ejecutivo", "Apoyo" }));

        jLabel1.setText("Categoria Ocupacional:");

        jLabel3.setText("Nombre:");

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Unidad Organizativa:");

        jLabel6.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(225, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(134, 134, 134)
                                .addComponent(nombreuo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre)
                                    .addComponent(tipo)
                                    .addComponent(salario)
                                    .addComponent(grupoescala)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(resolusion)
                                        .addComponent(calif))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GrupoescalajTextField1)
                                    .addComponent(nombrejTextField1)
                                    .addComponent(salariojTextField1)
                                    .addComponent(resolusionjTextField1)
                                    .addComponent(califjComboBox1, 0, 142, Short.MAX_VALUE)
                                    .addComponent(tipojComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombrejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupoescala)
                    .addComponent(GrupoescalajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salario)
                    .addComponent(salariojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolusion)
                    .addComponent(resolusionjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(califjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calif))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipojComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(nombreuo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertar)
                    .addComponent(cancelar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrejTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrejTextField1KeyPressed
       ValidaLetras.txtletras(evt);
    }//GEN-LAST:event_nombrejTextField1KeyPressed

    private void GrupoescalajTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrupoescalajTextField1KeyPressed
        ValidaLetras.txtletras(evt);
    }//GEN-LAST:event_GrupoescalajTextField1KeyPressed

    private void salariojTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salariojTextField1KeyPressed
        ValidaNumeros.txtnumero(evt);
    }//GEN-LAST:event_salariojTextField1KeyPressed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        
        boolean b= enableAcceptButton ();
        if (b!= false){
        Cargo c = new Cargo ();
        CategoriaOcuapcional co =new CategoriaOcuapcional();
        UnidadOrganizativa uo= new UnidadOrganizativa(); 
     
        c.setNombre(nombrejTextField1.getText());
        c.setCalificacion( (String)califjComboBox1.getSelectedItem());
        c.setGrupoEscala(GrupoescalajTextField1.getText());
        c.setResolucion(resolusionjTextField1.getText());
        c.setSalario( Float.parseFloat(salariojTextField1.getText()));
        c.setTipo((String)tipojComboBox2.getSelectedItem());
          
        String nombuo=((String)nombreuo.getSelectedItem());
        String nombco=((String)nombreco.getSelectedItem());
        
            try {
                CapitalHumano.addCargo(c,nombuo,nombco);
                String message = "El Cargo fue insertado exitosamente";
                //String message = "co="+co.getId() + "--- uo=" + uo.getIdentificadorUO();
                JOptionPane.showOptionDialog(getContentPane(), message, "Información", JOptionPane.YES_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, new Object[] {"Aceptar"}, "Aceptar");
                resetcomponents();
            }catch (SQLException e) {
                   Logger.getLogger(InsertarCargo.class.getName()).log(Level.SEVERE, null, e);
                   String message = "Ha ocurrido un error en la base de datos";
                   JOptionPane.showOptionDialog(getContentPane(), message, "Errot", JOptionPane.YES_OPTION,
                        JOptionPane.ERROR_MESSAGE, null, new Object[] {"Aceptar"}, "Aceptar");
            }catch (Exception ex) {
                Logger.getLogger(InsertarCargo.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showOptionDialog(getContentPane(), ex.getMessage(), "Errot", JOptionPane.YES_OPTION,
                       JOptionPane.ERROR_MESSAGE, null, new Object[] {"Aceptar"}, "Aceptar");     
          }
      }else {insertar.setEnabled(false);
         String message = "Debe llenar todos los campos del formulario";
         JOptionPane.showOptionDialog(getContentPane(), message, "Error", JOptionPane.YES_OPTION, 
        JOptionPane.INFORMATION_MESSAGE, null, new Object[] {"Aceptar"}, "Aceptar");
         insertar.setEnabled(true);}   
            

    }//GEN-LAST:event_insertarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {
            List<CategoriaOcuapcional> list = CapitalHumano.getAllCO();
            for(CategoriaOcuapcional item : list)
            {
                nombreco.addItem(item.getNombre());
                
            }
            List<UnidadOrganizativa> list1 = CapitalHumano.getAllUO();
            for(UnidadOrganizativa item : list1)
            {
                nombreuo.addItem(item.getNombre());
                
            }
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InsertarCargo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GrupoescalajTextField1;
    private javax.swing.JLabel calif;
    private javax.swing.JComboBox califjComboBox1;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel grupoescala;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nombre;
    private javax.swing.JComboBox nombreco;
    private javax.swing.JTextField nombrejTextField1;
    private javax.swing.JComboBox nombreuo;
    private javax.swing.JLabel resolusion;
    private javax.swing.JTextField resolusionjTextField1;
    private javax.swing.JLabel salario;
    private javax.swing.JTextField salariojTextField1;
    private javax.swing.JLabel tipo;
    private javax.swing.JComboBox tipojComboBox2;
    // End of variables declaration//GEN-END:variables


private void resetcomponents() {
     
      //nombcojTextField1.setText("");
      //idcojTextField1.setText("");
      salariojTextField1.setText("");
      resolusionjTextField1.setText("");
      GrupoescalajTextField1.setText("");
      nombrejTextField1.setText("");
      insertar.setEnabled(true);
    }

private boolean enableAcceptButton (){
         return ( !salariojTextField1.getText().trim().equals("") && !GrupoescalajTextField1.getText().trim().equals("")&& !nombrejTextField1.getText().trim().equals(""));
   }

}