/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion;

import Gestion.CapitalHumano;
import Gestion.Cargo;
import Util.ValidaNumeros;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Salario extends javax.swing.JFrame {

    /**
     * Creates new form Salario
     */
    public Salario() {
        initComponents();
        resetcomponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        menor = new javax.swing.JRadioButton();
        mayor = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        aceptar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salarios");

        jLabel1.setText("Valor a Buscar:");

        salario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salarioKeyReleased(evt);
            }
        });

        menor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menor.setText("≤");
        menor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorActionPerformed(evt);
            }
        });
        menor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menorKeyReleased(evt);
            }
        });

        mayor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mayor.setText("≥");
        mayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mayorKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Grupo Escala", "Salario", "Nivel de Preparación"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(menor)
                        .addGap(57, 57, 57)
                        .addComponent(mayor)
                        .addGap(55, 55, 55)
                        .addComponent(buscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menor)
                    .addComponent(mayor)
                    .addComponent(buscar))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(aceptar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menorActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        Cargo c =  new Cargo();
        float value = Float.parseFloat(salario.getText());
        
        if (mayor.getSelectedObjects() != null){
            
         try{
             List<Cargo> cargos = CapitalHumano.getSalaryBigger(value);
             
             DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
             tableModel.setRowCount(0);
             for (Cargo element : cargos) {
               
                Object[] row = {element.getNombre(),element.getGrupoEscala(), element.getSalario(), element.getCalificacion()};
                tableModel.addRow(row);
             }
          resetcomponents();
          }catch (SQLException ex) {
            Logger.getLogger(CapitalHumano.class.getName()).log(Level.SEVERE, null, ex);
          }
        }else if(menor.getSelectedObjects() != null){
            try {
               List<Cargo> cargos = CapitalHumano.getSalaryLower(value);
                
               DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
               tableModel.setRowCount(0);
               for (Cargo element : cargos) {
               
                Object[] row = {element.getNombre(),element.getGrupoEscala(), element.getSalario(), element.getCalificacion()};
                tableModel.addRow(row);
                }
            resetcomponents();
            }catch (SQLException ex) {
             Logger.getLogger(CapitalHumano.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else {String message = "Debe marcar uno de los sentidos de búsqueda > ó <  ";
                JOptionPane.showOptionDialog(getContentPane(), message, "Información", JOptionPane.YES_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, new Object[] {"Aceptar"}, "Aceptar");}
                
               
    }//GEN-LAST:event_buscarActionPerformed

    private void salarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salarioKeyPressed
       ValidaNumeros.txtnumero(evt);
    }//GEN-LAST:event_salarioKeyPressed

    private void salarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salarioKeyReleased
   //   buscar.setEnabled(enableBuscarButton());
    }//GEN-LAST:event_salarioKeyReleased

    private void menorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menorKeyReleased
  //    buscar.setEnabled(enableBuscarButton());
    }//GEN-LAST:event_menorKeyReleased

    private void mayorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mayorKeyReleased
  //    buscar.setEnabled(enableBuscarButton());
    }//GEN-LAST:event_mayorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Salario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton mayor;
    private javax.swing.JRadioButton menor;
    private javax.swing.JTextField salario;
    // End of variables declaration//GEN-END:variables

    
private void resetcomponents() {
        salario.setText("");
        mayor.setSelected(false);
        menor.setSelected(false);
        //buscar.setEnabled(false);    
}    
/*private boolean enableBuscarButton (){
         return (! salario.getText().trim().equals("") && !menor.getSelectedObjects().equals(null) && !mayor.getSelectedObjects().equals(null));
   }
*/
}
