/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIS;

import Gestion.Salario;
import Gestion.EliminarCO;
import Gestion.InsertarCO;
import Gestion.ModificarCO;
import Gestion.InsertarCargo;
import Gestion.CatalogoUO;
import Gestion.EliminarCargo;
import Gestion.AsociarPlazas;
import Gestion.CatalogoCO;
import Gestion.EliminarUnidadO;
import Gestion.ModificarCargo;
import Gestion.CatalogoCargo;
import Gestion.ModificarUO;
import Gestion.InsertarUnidadO;
import Reportes.PlantilladeCargos;
import Reportes.Vacantes;
import Seguridad.Autenticar;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class PrincipalE extends javax.swing.JFrame {

    //ImageIcon icon= new ImageIcon("iconparaproy.png");
    //JLabel label = new JLabel(icon);
    public PrincipalE() {
    initComponents();
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation((screenSize.width - getWidth()) / 2, (screenSize.height - getHeight())/ 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        catco = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        catuo = new javax.swing.JMenuItem();
        catc = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        insco = new javax.swing.JMenuItem();
        insuo = new javax.swing.JMenuItem();
        insc = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        modco = new javax.swing.JMenuItem();
        moduo = new javax.swing.JMenuItem();
        modc = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        elico = new javax.swing.JMenuItem();
        eliuo = new javax.swing.JMenuItem();
        elic = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        asoplaz = new javax.swing.JMenuItem();
        generar = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        vacantes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        salario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cambiarusu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Capital Humano");

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        catco.setText("Catálogos");
        catco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catcoActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Categorías ocupacionales");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        catco.add(jMenuItem5);

        catuo.setText("Unidades Organizativas");
        catuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catuoActionPerformed(evt);
            }
        });
        catco.add(catuo);

        catc.setText("Cargos");
        catc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catcActionPerformed(evt);
            }
        });
        catco.add(catc);

        jMenuBar1.add(catco);

        jMenu5.setText("Gestionar");

        jMenu7.setText("Insertar");

        insco.setText("Categoría Ocupacional");
        insco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscoActionPerformed(evt);
            }
        });
        jMenu7.add(insco);

        insuo.setText("Unidad Organizativa");
        insuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuoActionPerformed(evt);
            }
        });
        jMenu7.add(insuo);

        insc.setText("Cargo");
        insc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscActionPerformed(evt);
            }
        });
        jMenu7.add(insc);

        jMenu5.add(jMenu7);

        jMenu6.setText("Modificar");

        modco.setText("Categoría Ocupacional");
        modco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modcoActionPerformed(evt);
            }
        });
        jMenu6.add(modco);

        moduo.setText("Unidad Organizativa");
        moduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduoActionPerformed(evt);
            }
        });
        jMenu6.add(moduo);

        modc.setText("Cargo");
        modc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modcActionPerformed(evt);
            }
        });
        jMenu6.add(modc);

        jMenu5.add(jMenu6);

        jMenu8.setText("Eliminar");

        elico.setText("Categoría Ocupacional");
        elico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elicoActionPerformed(evt);
            }
        });
        jMenu8.add(elico);

        eliuo.setText("Unidad Organizativa");
        eliuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliuoActionPerformed(evt);
            }
        });
        jMenu8.add(eliuo);

        elic.setText("Cargo");
        elic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elicActionPerformed(evt);
            }
        });
        jMenu8.add(elic);

        jMenu5.add(jMenu8);

        jMenuBar1.add(jMenu5);

        jMenu9.setText("Plantilla");

        asoplaz.setText("Asociar Plazas");
        asoplaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asoplazActionPerformed(evt);
            }
        });
        jMenu9.add(asoplaz);

        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        jMenu9.add(generar);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Reportes");

        vacantes.setText("Plazas Vacantes");
        vacantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacantesActionPerformed(evt);
            }
        });
        jMenu10.add(vacantes);

        jMenuBar1.add(jMenu10);

        jMenu2.setText("Buscar");

        salario.setText("Salarios");
        salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioActionPerformed(evt);
            }
        });
        jMenu2.add(salario);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Configuración");

        cambiarusu.setText("Cambiar de Usuario");
        cambiarusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarusuActionPerformed(evt);
            }
        });
        jMenu4.add(cambiarusu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catcoActionPerformed
        new CatalogoCO().setVisible(true);
    }//GEN-LAST:event_catcoActionPerformed

    private void catuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catuoActionPerformed
        new CatalogoUO().setVisible(true);
    }//GEN-LAST:event_catuoActionPerformed

    private void inscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscoActionPerformed
       new InsertarCO().setVisible(true);
    }//GEN-LAST:event_inscoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new CatalogoCO().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void catcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catcActionPerformed
       new CatalogoCargo().setVisible(true);
    }//GEN-LAST:event_catcActionPerformed

    private void insuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuoActionPerformed
         new InsertarUnidadO().setVisible(true);
    }//GEN-LAST:event_insuoActionPerformed

    private void inscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscActionPerformed
       new InsertarCargo().setVisible(true);
    }//GEN-LAST:event_inscActionPerformed

    private void modcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modcoActionPerformed
         new ModificarCO().setVisible(true);
    }//GEN-LAST:event_modcoActionPerformed

    private void moduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduoActionPerformed
        new ModificarUO().setVisible(true);
    }//GEN-LAST:event_moduoActionPerformed

    private void modcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modcActionPerformed
        new ModificarCargo().setVisible(true);
    }//GEN-LAST:event_modcActionPerformed

    private void elicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elicoActionPerformed
         new EliminarCO().setVisible(true);
    }//GEN-LAST:event_elicoActionPerformed

    private void eliuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliuoActionPerformed
        new EliminarUnidadO().setVisible(true);
    }//GEN-LAST:event_eliuoActionPerformed

    private void elicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elicActionPerformed
       new EliminarCargo().setVisible(true);
    }//GEN-LAST:event_elicActionPerformed

    private void asoplazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asoplazActionPerformed
       new AsociarPlazas().setVisible(true);
    }//GEN-LAST:event_asoplazActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
         new PlantilladeCargos().setVisible(true);
    }//GEN-LAST:event_generarActionPerformed

    private void vacantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacantesActionPerformed
         new Vacantes().setVisible(true);
    }//GEN-LAST:event_vacantesActionPerformed

    private void cambiarusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarusuActionPerformed
       new Autenticar().setVisible(true);
       dispose();
    }//GEN-LAST:event_cambiarusuActionPerformed

    private void salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioActionPerformed
      new Salario().setVisible(true);
    }//GEN-LAST:event_salarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PrincipalE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem asoplaz;
    private javax.swing.JMenuItem cambiarusu;
    private javax.swing.JMenuItem catc;
    private javax.swing.JMenu catco;
    private javax.swing.JMenuItem catuo;
    private javax.swing.JMenuItem elic;
    private javax.swing.JMenuItem elico;
    private javax.swing.JMenuItem eliuo;
    private javax.swing.JMenuItem generar;
    private javax.swing.JMenuItem insc;
    private javax.swing.JMenuItem insco;
    private javax.swing.JMenuItem insuo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem modc;
    private javax.swing.JMenuItem modco;
    private javax.swing.JMenuItem moduo;
    private javax.swing.JMenuItem salario;
    private javax.swing.JMenuItem vacantes;
    // End of variables declaration//GEN-END:variables
}
